language: erlang
otp_release:
  - 21.0.4
  - 20.3.8.2
  - 19.3
  - 18.3
install:
  - wget https://s3.amazonaws.com/rebar3/rebar3 && chmod u+x rebar3
  - REBAR=./rebar3 make
  - ./rebar3 update
script:
  - REBAR=./rebar3 make eunit
  - REBAR=./rebar3 make ct
  - REBAR=./rebar3 make proper
  - REBAR=./rebar3 make xref
  - REBAR=./rebar3 make dialyzer
  - REBAR=./rebar3 make lint
notifications:
  email: christopher.meiklejohn@gmail.com
  slack: lasp-lang:hiPRNnbUa3zdGrrXZfGRAF7D
  irc: "irc.freenode.org#lasp-lang"
sudo: false
